const copy = {
  en: {eyebrow:"Local Codex Tool · macOS",headline:"Your session.<br><span>Your simulator.</span>",lead:"A fair, pressure-aware control plane for iOS Simulators and Android Emulators across every Codex task on your Mac.",download:"Download Tool",installNow:"Install in one command",compat:"macOS 13+ · Python 3.9+ · Xcode or Android SDK when needed",healthy:"Healthy",pressure:"HOST PRESSURE",dynamic:"Dynamic",privateReady:"3 private slots ready",activeLease:"ACTIVE LEASE",queue:"FIFO QUEUE",yieldIn:"Safe yield in 38s",running:"RUNNING",queued:"QUEUED",waiting:"WAITING",foregroundLane:"Foreground desktop lane",howKicker:"HOW IT WORKS",howTitle:"Codex asks. The manager schedules. Your test runs safely.",howBody:"Builds and unit tests stay on the host. Only runtime or UI checks enter the managed lane, use one exact device, then release automatically.",flowRequest:"Requests runtime validation",flowSchedule:"Checks pressure + FIFO",flowDevice:"Assigned device",flowRelease:"Runs, verifies, releases",privateTitle:"Private by default",privateBody:"Each session and project keeps a stable simulator environment and device data.",fairTitle:"Fair under load",fairBody:"A 10-minute total budget, bounded renewals, and 2-minute slices when someone waits.",pressureTitle:"Pressure aware",pressureBody:"Concurrency steps down gradually to Traditional FIFO before the Mac becomes overloaded.",releaseTitle:"Guaranteed release",releaseBody:"Supervised work releases on success, failure, interruption, timeout, or safe yield.",installKicker:"INSTALL",installTitle:"One command. One sentence in Codex.",installBody:"The installer adds the CLI, Skill, public marketplace, and Plugin to your user account. It uses no sudo and refuses to replace active or unmanaged installations.",copy:"Copy",thenSay:"Then start a new task and say",prompt:"Use simulator-manager for this project.",downloadZip:"Download ZIP",checksum:"SHA-256 checksum",docs:"Full documentation",default:"DEFAULT",dynamicTitle:"Dynamic Simulator Pool",dynamicBody:"Creates stable private iOS and Android environments lazily. Parallel work is admitted only while host resources allow it.",fallback:"AUTOMATIC FALLBACK",traditionalTitle:"Traditional FIFO",traditionalBody:"When pressure rises, work uses a bounded shared pool in queue order. Existing private data and active work stay protected.",privacyTitle:"Local by design",privacyBody:"Scheduling state, device identities, and test output stay on your Mac. Simulator Manager has no account, cloud service, analytics, or telemetry.",portfolio:"AI Hank Apps",copied:"Copied"},
  "zh-Hant": {eyebrow:"本機 Codex 工具 · macOS",headline:"你的工作階段。<br><span>你的模擬器。</span>",lead:"在同一台 Mac 的所有 Codex 任務之間，公平且能感知效能壓力地管理 iOS Simulator 與 Android Emulator。",download:"下載工具",installNow:"一行指令安裝",compat:"macOS 13+ · Python 3.9+ · 依平台使用 Xcode 或 Android SDK",healthy:"運作正常",pressure:"主機效能壓力",dynamic:"動態模式",privateReady:"3 個私人環境可用",activeLease:"使用中的租約",queue:"FIFO 排隊",yieldIn:"38 秒後安全讓出",running:"執行中",queued:"排隊中",waiting:"等待中",foregroundLane:"前景桌面操作通道",howKicker:"運作方式",howTitle:"Codex 提出需求，管理器負責排程，測試安全執行。",howBody:"建置與單元測試先在主機完成。只有 runtime 或 UI 驗證才進入受管理通道，使用唯一指定裝置並自動釋放。",flowRequest:"提出 runtime 驗證需求",flowSchedule:"檢查效能與 FIFO",flowDevice:"分配指定裝置",flowRelease:"執行、驗證、釋放",privateTitle:"預設私人環境",privateBody:"每個工作階段與專案保有固定的模擬器環境和裝置資料。",fairTitle:"繁忙時保持公平",fairBody:"總占用上限 10 分鐘、續租次數有限；有人等待時每 2 分鐘安全讓出。",pressureTitle:"自動感知效能",pressureBody:"主機負載升高時逐步降低並行量，最後切換為傳統 FIFO。",releaseTitle:"保證釋放",releaseBody:"成功、失敗、中斷、逾時或安全讓出時，受監督工作都會釋放資源。",installKicker:"安裝",installTitle:"一行指令，再對 Codex 說一句話。",installBody:"安裝器會把 CLI、Skill、公開 marketplace 與 Plugin 安裝到你的使用者帳號；不需要 sudo，也不會覆蓋使用中或不受管理的安裝。",copy:"複製",thenSay:"接著開啟新的 Codex 任務並輸入",prompt:"這個專案使用 simulator-manager。",downloadZip:"下載 ZIP",checksum:"SHA-256 校驗碼",docs:"完整說明文件",default:"預設模式",dynamicTitle:"Dynamic Simulator Pool",dynamicBody:"按需建立固定的私人 iOS 與 Android 環境；只有主機資源足夠時才允許並行工作。",fallback:"自動降級",traditionalTitle:"Traditional FIFO",traditionalBody:"主機壓力升高時改用容量受限的共用資源池並依序排隊；既有私人資料和執行中的工作都會受到保護。",privacyTitle:"從設計上保持本機運作",privacyBody:"排程狀態、裝置識別與測試輸出都留在你的 Mac。Simulator Manager 不需要帳號，也沒有雲端服務、分析或遙測。",portfolio:"AI Hank Apps 作品集",copied:"已複製"}
};

const normalize = value => value && value.toLowerCase().startsWith("zh") ? "zh-Hant" : "en";
const query = new URLSearchParams(location.search).get("lang");
let lang = query ? normalize(query) : (localStorage.getItem("simManagerLang") || normalize(navigator.languages?.[0] || navigator.language));
function applyLanguage(next){lang=normalize(next);localStorage.setItem("simManagerLang",lang);document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const value=copy[lang][el.dataset.i18n];if(value!==undefined)el.innerHTML=value});document.querySelectorAll("[data-lang]").forEach(button=>button.classList.toggle("active",button.dataset.lang===lang));document.title=lang==="zh-Hant"?"Simulator Manager — Codex 共用模擬器管理工具":"Simulator Manager — Shared mobile testing for Codex"}
document.querySelectorAll("[data-lang]").forEach(button=>button.addEventListener("click",()=>applyLanguage(button.dataset.lang)));
document.querySelectorAll("[data-copy]").forEach(button=>button.addEventListener("click",()=>copyText(button.dataset.copy)));
document.querySelectorAll("[data-copy-key]").forEach(button=>button.addEventListener("click",()=>copyText(copy[lang][button.dataset.copyKey])));
function copyText(value){navigator.clipboard.writeText(value).then(()=>{const toast=document.querySelector(".toast");toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1400)})}
applyLanguage(lang);
